FROM node:22

WORKDIR /app

COPY package*.json ./
COPY .npmrc ./
COPY prisma ./prisma/

RUN npm install --only=production

RUN npm install @nestjs/cli typescript --global

COPY . .

RUN npx prisma generate

RUN npm run build

RUN npm prune --production

EXPOSE 4000

CMD ["npm", "run", "start:migrate:dev"]
